version: '3.3'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 8081:8080
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ${PWD}/zookeeper/zoo.cfg:/conf/zoo.cfg

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 2
    volumes:
      - ${PWD}/zookeeper/zoo.cfg:/conf/zoo.cfg

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
      - 8083:8080
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ${PWD}/zookeeper/zoo.cfg:/conf/zoo.cfg

